### ISSUE TITLE
make podeno to action

### ISSUE THREAD

**Issue by Omochice** [Omochice/dotfiles#64]
It is usefull to reuse other repository.

like:

```yml
    - use: Omochice/action-podeno
      opt:
        - in: some pod file path
          out: some output file path
          type: markdown
        - in: some pod file path
          out: some output file path
          type: vimdoc
```
