### ISSUE TITLE
pathをいい感じに設定する何かをつくる

### ISSUE THREAD

**Issue by Omochice** [Omochice/dotfiles#9]
bash,zsh,fishを行き来するのでいい感じにPATHを設定するやつを作りたい

tomlに次のようにかく

```toml
[[paths]]
path = "~/.local/bin"
hook_bash = """
source iikanji-completion.bash
"""
hook_zsh = """
source iikanji-completion.zsh
"""
```

これを`$(shell)`の値かコマンドライン引数で書き出すもの
